### ISSUE TITLE
`quicklook` crashes with some tests

### ISSUE THREAD

**Issue by ziotom78** [satorchi/qubicpack#4]
Running `quicklook` on test [`2009-06-09_05.33.15__Essai`](https://hesabu.fisica.unimi.it/api/v1/acquisitions/2009-06-09T05:33:15) produces the following error:

```
Traceback (most recent call last):
  File "qutedb_crawler/__init__.py", line 169, in <module>
    main()
  File "qutedb_crawler/__init__.py", line 165, in main
    process_folders(rootpath=args.folder, always_make=args.always_make)
  File "qutedb_crawler/__init__.py", line 123, in process_folders
    create_plot(testpath=curentry, always_make=always_make)
  File "qutedb_crawler/__init__.py", line 44, in create_plot
    filename = a.quicklook(xwin=False)
  File "/home/tomasi/.cache/pypoetry/virtualenvs/qutedb-crawler-u7XHjgr2-py3.7/src/qubicpack/qubicpack/quicklook.py", line 348, in quicklook
    self.plot_calsource(ax,fontsize=fontsize)
  File "/home/tomasi/.cache/pypoetry/virtualenvs/qutedb-crawler-u7XHjgr2-py3.7/src/qubicpack/qubicpack/quicklook.py", line 22, in plot_calsource
    pngname = 'QUBIC_calsource_%s_%s.png' % (dset_shortname,self.obsdate.strftime('%Y%m%d-%H%M%S'))
AttributeError: 'NoneType' object has no attribute 'strftime'
```

**Comment by satorchi** [comment]
I have fixed this problem so that it will correctly deal with older datasets which do not have the same metadata structure (backwards compatibility).  The plot produced might have some empty boxes, but that's ok.

I've also fixed the issue of crashing on corrupted or unfinished FITS files.  In this case, quicklook will produce a plot with whatever data it managed to extract (housekeeping or scientific).

Finally, in case there is no data at all, quicklook() will return None and there will be no plot produced.

Please tell me if you still find problem datasets.

Thanks for posting the issue!
Cheers,
Steve
